<?if(!defined("B_PROLOG_INCLUDED") || B_PROLOG_INCLUDED!==true)die();?>
<?
$aMenuLinks = Array(
    Array(
        "Новости",
        "/news/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Команда",
        "/team/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Клуб",
        "/club/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Медиа",
        "/media/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Волейград",
        "/about/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Анкета для вступления в клуб",
        "https://academy.volleygrad.ru/anketa_2",
        Array(),
        Array(),
        ""
    )
);
?>