<?if(!defined("B_PROLOG_INCLUDED") || B_PROLOG_INCLUDED!==true)die();?>
<?
$aMenuLinks = Array(
	Array(
		"Руководство",
		"/club/",
		Array(),
        Array(),
        ""
	),
    Array(
        "История",
        "/club/istoriya/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Арена",
        "/club/arena/",
        Array(),
        Array(),
        ""
    ),
	Array(
		"Спонсорам и партнерам",
		"/club/sponrors/",
		Array(), 
		Array(),
		"" 
	),
	Array(
		"Контакты",
		"/club/contacts/",
		Array(),
		Array(),
		""
	)
);
?>